name: 'Detect Laravel Ray Action'
description: 'Scan your Laravel application and fails if it detects remaining Spatie\ray calls ("ray()" or "@ray()")'
branding:
  icon: 'check-square'
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/check-ray-calls.sh
      shell: bash
