name: 'Detect Laravel Ray Action'
description: 'Detect remaining Spatie\ray calls in a Laravel application. The current workflow will fail if a "ray()" or "@ray()" is found in the code'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/check-ray-calls.sh
      shell: bash
